// Business Register
export const BUSINESS_REGISTER_REQUEST = 'BUSINESS_REGISTER_REQUEST';
export const BUSINESS_REGISTER_SUCCESS = 'BUSINESS_REGISTER_SUCCESS';
export const BUSINESS_REGISTER_FAIL = 'BUSINESS_REGISTER_FAIL';

// Business Login
export const BUSINESS_LOGIN_REQUEST = 'BUSINESS_LOGIN_REQUEST';
export const BUSINESS_LOGIN_SUCCESS = 'BUSINESS_LOGIN_SUCCESS';
export const BUSINESS_LOGIN_FAIL = 'BUSINESS_LOGIN_FAIL';

// Business Logout
export const BUSINESS_LOGOUT = 'BUSINESS_LOGOUT';

// Fetch Business
export const FETCH_BUSINESS_REQUEST = 'FETCH_BUSINESS_REQUEST';
export const FETCH_BUSINESS_SUCCESS = 'FETCH_BUSINESS_SUCCESS';
export const FETCH_BUSINESS_FAILURE = 'FETCH_BUSINESS_FAILURE';

// Update Business
export const UPDATE_BUSINESS_REQUEST = 'UPDATE_BUSINESS_REQUEST';
export const UPDATE_BUSINESS_SUCCESS = 'UPDATE_BUSINESS_SUCCESS';
export const UPDATE_BUSINESS_FAILURE = 'UPDATE_BUSINESS_FAILURE';

// Upload Business Photo
export const UPLOAD_BUSINESS_PHOTO_REQUEST = 'UPLOAD_BUSINESS_PHOTO_REQUEST';
export const UPLOAD_BUSINESS_PHOTO_SUCCESS = 'UPLOAD_BUSINESS_PHOTO_SUCCESS';
export const UPLOAD_BUSINESS_PHOTO_FAILURE = 'UPLOAD_BUSINESS_PHOTO_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const OTP_REQUEST = 'OTP_REQUEST';
export const OTP_VERIFIED = 'OTP_VERIFIED';
export const OTP_FAILED = 'OTP_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';
export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST';
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS';
export const USER_FORGOT_PASSWORD_FAIL = 'USER_FORGOT_PASSWORD_FAIL';

export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST';
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS';
export const USER_RESET_PASSWORD_FAIL = 'USER_RESET_PASSWORD_FAIL';

export const BUSINESS_LIST_REQUEST = 'BUSINESS_LIST_REQUEST';
export const BUSINESS_LIST_SUCCESS = 'BUSINESS_LIST_SUCCESS';
export const BUSINESS_LIST_FAIL = 'BUSINESS_LIST_FAIL';

// review
export const SUBMIT_REVIEW_REQUEST = 'SUBMIT_REVIEW_REQUEST';
export const SUBMIT_REVIEW_SUCCESS = 'SUBMIT_REVIEW_SUCCESS';
export const SUBMIT_REVIEW_FAILURE = 'SUBMIT_REVIEW_FAILURE';

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_FAILURE = 'GET_REVIEWS_FAILURE';

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAILURE = 'DELETE_REVIEW_FAILURE';

export const UPDATE_REVIEW_REQUEST = 'UPDATE_REVIEW_REQUEST';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_FAILURE = 'UPDATE_REVIEW_FAILURE';

export const FETCH_REVIEWS_REQUEST = 'FETCH_REVIEWS_REQUEST';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAILURE = 'FETCH_REVIEWS_FAILURE';

export const EDIT_REVIEW_REQUEST = 'EDIT_REVIEW_REQUEST';
export const EDIT_REVIEW_SUCCESS = 'EDIT_REVIEW_SUCCESS';
export const EDIT_REVIEW_FAILURE = 'EDIT_REVIEW_FAILURE';

export const FETCH_ALL_BUSINESSES_REQUEST = 'FETCH_ALL_BUSINESSES_REQUEST';
export const FETCH_ALL_BUSINESSES_SUCCESS = 'FETCH_ALL_BUSINESSES_SUCCESS';
export const FETCH_ALL_BUSINESSES_FAILURE = 'FETCH_ALL_BUSINESSES_FAILURE';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';

export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL';

// types.js

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST';

// For sending OTP
export const OTP_SENT_SUCCESS = 'OTP_SENT_SUCCESS';
export const OTP_SENT_FAILED = 'OTP_SENT_FAILED';

// For verifying OTP
export const OTP_VERIFIED_SUCCESS = 'OTP_VERIFIED_SUCCESS';
export const OTP_VERIFIED_FAILED = 'OTP_VERIFIED_FAILED';




