// User authentication
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

// User registration
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// OTP verification 
export const OTP_REQUEST = 'OTP_REQUEST';
export const OTP_VERIFIED = 'OTP_VERIFIED';
export const OTP_FAILED = 'OTP_FAILED';

// forgot password
export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST';
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS';
export const USER_FORGOT_PASSWORD_FAIL = 'USER_FORGOT_PASSWORD_FAIL';

// reset password
export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST';
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS';
export const USER_RESET_PASSWORD_FAIL = 'USER_RESET_PASSWORD_FAIL';

// Business registration 
export const BUSINESS_REGISTER_REQUEST = 'BUSINESS_REGISTER_REQUEST';
export const BUSINESS_REGISTER_SUCCESS = 'BUSINESS_REGISTER_SUCCESS';
export const BUSINESS_REGISTER_FAIL = 'BUSINESS_REGISTER_FAIL';

// Business login
export const BUSINESS_LOGIN_REQUEST = 'BUSINESS_LOGIN_REQUEST';
export const BUSINESS_LOGIN_SUCCESS = 'BUSINESS_LOGIN_SUCCESS';
export const BUSINESS_LOGIN_FAIL = 'BUSINESS_LOGIN_FAIL';
export const BUSINESS_LOGOUT = 'BUSINESS_LOGOUT';


// // OTP
// export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
// export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
// export const SEND_OTP_FAIL = 'SEND_OTP_FAIL';
// export const OTP_SENT = 'OTP_SENT';
// export const OTP_FAILED = 'OTP_FAILED';

// User data
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

// Clear errors
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
